# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1475a954c68c734277312b741836f1c9b24b1c025f06141a874fce01cdcbfc15639cd4c4ffc58e6d084d8a34dab1e3fca77c1c0e59c49f9d399e063c5f804e8

test:
  secret_key_base: ce50b6996af2bced2b5c3ba2d34797600378f1c6d1418c58a2977d63318ceec1b631f2f6e287e2617a05a65cec767625d8561fc4f6c827908053fdc52f79623a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
